### ISSUE TITLE
Issue with tab bar icon

### ISSUE THREAD

**Issue by Keyur2456** [simformsolutions/SSCustomTabbar#21] opened 2020-05-09 13:49 UTC
Need help to solve out this issue.
![Issue with first tab bar option](https://user-images.githubusercontent.com/29301551/81475451-f16d2d80-9229-11ea-8017-c89e31565d5f.gif)

**Comment by kalaichelvan** [comment] 2020-06-02 18:09
Is there any solution so far for this problem? When the app is launched, first tabbar item is raised slightly higher. However if the device is rotated, the icon is being  positioned correctly. 


![Simulator Screen Shot - iPhone 11 - 2020-06-03 at 02 08 37](https://user-images.githubusercontent.com/3763151/83554314-29247800-a53f-11ea-8652-904a8cf64979.png)

**Comment by amitmoradiya0611** [comment] 2020-07-06 07:41
Hey,

I fixed this using this : 

just put : defaultIndexValue = 0 in SSCustomTabBarViewController.swift

Make sure to clean build folder after updating before run app if you're using pod

Thanks.

**Comment by vraj-s-shah** [comment] 2022-11-03 10:40
This issue has been fixed and merged to develop and it will be available in next release.

**Comment by mobile-simformsolutions** [comment] 2022-11-30 05:27
@Keyur2456 @kalaichelvan The issue is fixed in the latest release version [2.0.7](https://github.com/SimformSolutionsPvtLtd/SSCustomTabbar/tree/2.0.7).

**Closed as completed by mobile-simformsolutions** 2022-11-30 05:27 UTC
Labels: bug
